2025-05-22 15:25:55,159 - app.main - INFO - BTP Civil Status Service starting, logs will be saved to: logs/btp_service_20250522.txt
2025-05-22 15:25:55,164 - app.main - INFO - Civil Status Service starting up...
2025-05-22 15:25:55,164 - app.services.outbox_processor - INFO - Outbox processor started
2025-05-22 15:25:55,164 - app.services.event_retry_worker - INFO - Event retry worker started
2025-05-22 15:25:55,164 - app.services.reconciliation - INFO - Reconciliation service started
2025-05-22 15:25:55,294 - app.services.reconciliation - INFO - Starting marriage records consistency check
2025-05-22 15:25:55,300 - app.services.reconciliation - INFO - No marriage inconsistencies found
2025-05-22 15:25:55,301 - app.services.reconciliation - INFO - Starting death records consistency check
2025-05-22 15:30:55,253 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 15:30:55,254 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-22 15:30:55,254 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. 
2025-05-22 16:25:55,302 - app.services.reconciliation - INFO - Starting marriage records consistency check
2025-05-22 16:25:55,307 - app.services.reconciliation - INFO - No marriage inconsistencies found
2025-05-22 16:25:55,307 - app.services.reconciliation - INFO - Starting death records consistency check
2025-05-22 17:25:55,307 - app.services.reconciliation - INFO - Starting marriage records consistency check
2025-05-22 17:25:55,315 - app.services.reconciliation - INFO - No marriage inconsistencies found
2025-05-22 17:25:55,316 - app.services.reconciliation - INFO - Starting death records consistency check
2025-05-22 17:38:09,619 - app.api.router - INFO - Request to get death certificate with ID: 1
2025-05-22 17:38:09,632 - app.db.civil_status_repo - ERROR - Database error getting death certificate by ID 1: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'Reference.Wards'. (208) (SQLExecDirectW)")
[SQL: 
                SELECT 
                    dc.*,
                    w.ward_name AS place_of_death_ward_name,
                    d.district_name AS place_of_death_district_name,
                    p.province_name AS place_of_death_province_name,
                    a.authority_name AS issuing_authority_name
                FROM 
                    [BTP].[DeathCertificate] dc
                    LEFT JOIN [Reference].[Wards] w ON dc.place_of_death_ward_id = w.ward_id
                    LEFT JOIN [Reference].[Districts] d ON dc.place_of_death_district_id = d.district_id
                    LEFT JOIN [Reference].[Provinces] p ON dc.place_of_death_province_id = p.province_id
                    LEFT JOIN [Reference].[Authorities] a ON dc.issuing_authority_id = a.authority_id
                WHERE 
                    dc.death_certificate_id = ?
            ]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "/home/duyhung/Desktop/DATN/myenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/duyhung/Desktop/DATN/myenv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'Reference.Wards'. (208) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/duyhung/Desktop/DATN/citizen-management-system_v5/service/be/civil_status_service_btp/app/db/civil_status_repo.py", line 103, in get_death_certificate_by_id
    result = self.db.execute(query, {"certificate_id": certificate_id}).fetchone()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duyhung/Desktop/DATN/myenv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duyhung/Desktop/DATN/myenv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2260, in _execute_internal
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/duyhung/Desktop/DATN/myenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "/home/duyhung/Desktop/DATN/myenv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duyhung/Desktop/DATN/myenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duyhung/Desktop/DATN/myenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duyhung/Desktop/DATN/myenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/duyhung/Desktop/DATN/myenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/duyhung/Desktop/DATN/myenv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/duyhung/Desktop/DATN/myenv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'Reference.Wards'. (208) (SQLExecDirectW)")
[SQL: 
                SELECT 
                    dc.*,
                    w.ward_name AS place_of_death_ward_name,
                    d.district_name AS place_of_death_district_name,
                    p.province_name AS place_of_death_province_name,
                    a.authority_name AS issuing_authority_name
                FROM 
                    [BTP].[DeathCertificate] dc
                    LEFT JOIN [Reference].[Wards] w ON dc.place_of_death_ward_id = w.ward_id
                    LEFT JOIN [Reference].[Districts] d ON dc.place_of_death_district_id = d.district_id
                    LEFT JOIN [Reference].[Provinces] p ON dc.place_of_death_province_id = p.province_id
                    LEFT JOIN [Reference].[Authorities] a ON dc.issuing_authority_id = a.authority_id
                WHERE 
                    dc.death_certificate_id = ?
            ]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-22 17:42:18,572 - app.main - INFO - Civil Status Service shutting down...
2025-05-22 17:42:18,572 - app.services.reconciliation - INFO - Reconciliation service stopped
2025-05-22 17:42:18,572 - app.services.outbox_processor - INFO - Outbox processor stopped
2025-05-22 17:42:18,572 - app.services.event_retry_worker - INFO - Event retry worker stopped
2025-05-22 17:42:18,572 - kafka.producer.kafka - INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
2025-05-22 17:42:18,573 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. 
2025-05-22 17:42:18,573 - app.services.kafka_producer - INFO - Kafka producer closed.
2025-05-22 17:42:19,227 - app.main - INFO - BTP Civil Status Service starting, logs will be saved to: logs/btp_service_20250522.txt
2025-05-22 17:42:19,230 - app.main - INFO - Civil Status Service starting up...
2025-05-22 17:42:19,230 - app.services.outbox_processor - INFO - Outbox processor started
2025-05-22 17:42:19,231 - app.services.event_retry_worker - INFO - Event retry worker started
2025-05-22 17:42:19,231 - app.services.reconciliation - INFO - Reconciliation service started
2025-05-22 17:42:19,355 - app.services.reconciliation - INFO - Starting marriage records consistency check
2025-05-22 17:42:19,359 - app.services.reconciliation - INFO - No marriage inconsistencies found
2025-05-22 17:42:19,360 - app.services.reconciliation - INFO - Starting death records consistency check
2025-05-22 17:47:19,228 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 17:47:19,229 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-22 17:47:19,229 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. 
2025-05-22 17:59:35,060 - app.main - INFO - Civil Status Service shutting down...
2025-05-22 17:59:35,060 - app.services.reconciliation - INFO - Reconciliation service stopped
2025-05-22 17:59:35,060 - app.services.outbox_processor - INFO - Outbox processor stopped
2025-05-22 17:59:35,060 - app.services.event_retry_worker - INFO - Event retry worker stopped
2025-05-22 17:59:35,060 - kafka.producer.kafka - INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
2025-05-22 17:59:35,060 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. 
2025-05-22 17:59:35,061 - app.services.kafka_producer - INFO - Kafka producer closed.
2025-05-22 17:59:35,648 - app.main - INFO - BTP Civil Status Service starting, logs will be saved to: logs/btp_service_20250522.txt
2025-05-22 17:59:35,650 - app.main - INFO - Civil Status Service starting up...
2025-05-22 17:59:35,651 - app.services.outbox_processor - INFO - Outbox processor started
2025-05-22 17:59:35,651 - app.services.event_retry_worker - INFO - Event retry worker started
2025-05-22 17:59:35,651 - app.services.reconciliation - INFO - Reconciliation service started
2025-05-22 17:59:35,830 - app.services.reconciliation - INFO - Starting marriage records consistency check
2025-05-22 17:59:35,834 - app.services.reconciliation - INFO - No marriage inconsistencies found
2025-05-22 17:59:35,834 - app.services.reconciliation - INFO - Starting death records consistency check
2025-05-22 18:04:35,744 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:04:35,745 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-22 18:04:35,745 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. 
2025-05-22 18:19:25,412 - app.main - INFO - Civil Status Service shutting down...
2025-05-22 18:19:25,412 - app.services.reconciliation - INFO - Reconciliation service stopped
2025-05-22 18:19:25,412 - app.services.outbox_processor - INFO - Outbox processor stopped
2025-05-22 18:19:25,412 - app.services.event_retry_worker - INFO - Event retry worker stopped
2025-05-22 18:19:25,412 - kafka.producer.kafka - INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
2025-05-22 18:19:25,413 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. 
2025-05-22 18:19:25,413 - app.services.kafka_producer - INFO - Kafka producer closed.
2025-05-22 18:19:26,013 - app.main - INFO - BTP Civil Status Service starting, logs will be saved to: logs/btp_service_20250522.txt
2025-05-22 18:19:26,016 - app.main - INFO - Civil Status Service starting up...
2025-05-22 18:19:26,017 - app.services.outbox_processor - INFO - Outbox processor started
2025-05-22 18:19:26,017 - app.services.event_retry_worker - INFO - Event retry worker started
2025-05-22 18:19:26,017 - app.services.reconciliation - INFO - Reconciliation service started
2025-05-22 18:19:26,169 - app.services.reconciliation - INFO - Starting marriage records consistency check
2025-05-22 18:19:26,173 - app.services.reconciliation - INFO - No marriage inconsistencies found
2025-05-22 18:19:26,173 - app.services.reconciliation - INFO - Starting death records consistency check
2025-05-22 18:19:40,065 - app.api.router - INFO - Request to get death certificate with ID: 1
2025-05-22 18:19:40,082 - app.api.router - INFO - Fetching reference data for tables: ['Wards', 'Districts', 'Provinces', 'Authorities'] from BCA service.
2025-05-22 18:19:40,083 - app.api.router - ERROR - Unexpected error fetching reference data for death cert 1: 'BCAClient' object has no attribute 'get_reference_data'
Traceback (most recent call last):
  File "/home/duyhung/Desktop/DATN/citizen-management-system_v5/service/be/civil_status_service_btp/app/api/router.py", line 173, in get_death_certificate
    reference_data_from_bca = await bca_client.get_reference_data(ref_tables_to_fetch)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BCAClient' object has no attribute 'get_reference_data'
2025-05-22 18:22:21,035 - app.main - INFO - Civil Status Service shutting down...
2025-05-22 18:22:21,035 - app.services.reconciliation - INFO - Reconciliation service stopped
2025-05-22 18:22:21,035 - app.services.outbox_processor - INFO - Outbox processor stopped
2025-05-22 18:22:21,035 - app.services.event_retry_worker - INFO - Event retry worker stopped
2025-05-22 18:22:21,035 - kafka.producer.kafka - INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
2025-05-22 18:22:21,036 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. 
2025-05-22 18:22:21,036 - app.services.kafka_producer - INFO - Kafka producer closed.
2025-05-22 18:22:21,691 - app.main - INFO - BTP Civil Status Service starting, logs will be saved to: logs/btp_service_20250522.txt
2025-05-22 18:22:21,694 - app.main - INFO - Civil Status Service starting up...
2025-05-22 18:22:21,694 - app.services.outbox_processor - INFO - Outbox processor started
2025-05-22 18:22:21,694 - app.services.event_retry_worker - INFO - Event retry worker started
2025-05-22 18:22:21,694 - app.services.reconciliation - INFO - Reconciliation service started
2025-05-22 18:22:21,805 - app.services.reconciliation - INFO - Starting marriage records consistency check
2025-05-22 18:22:21,808 - app.services.reconciliation - INFO - No marriage inconsistencies found
2025-05-22 18:22:21,809 - app.services.reconciliation - INFO - Starting death records consistency check
2025-05-22 18:22:29,385 - app.api.router - INFO - Request to get death certificate with ID: 1
2025-05-22 18:22:29,393 - app.api.router - INFO - Fetching reference data for tables: ['Wards', 'Districts', 'Provinces', 'Authorities'] from BCA service.
2025-05-22 18:22:29,496 - httpx - INFO - HTTP Request: GET http://localhost:8000/api/v1/references/?tables=Wards%2CDistricts%2CProvinces%2CAuthorities "HTTP/1.1 200 OK"
2025-05-22 18:27:21,789 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:27:21,789 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-22 18:27:21,789 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. 
2025-05-22 18:28:26,438 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: Socket EVENT_READ without in-flight-requests
2025-05-22 18:28:26,438 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:26,439 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:26,440 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-22 18:28:26,441 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-22 18:28:26,441 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-22 18:28:26,442 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:26,544 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:26,545 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-22 18:28:26,548 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-22 18:28:26,549 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-22 18:28:26,549 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:26,651 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:26,651 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-22 18:28:26,652 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-22 18:28:26,652 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-22 18:28:26,652 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:26,753 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:26,753 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-22 18:28:26,754 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-22 18:28:26,754 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-22 18:28:26,754 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:26,855 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:26,855 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-22 18:28:26,856 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-22 18:28:26,856 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-22 18:28:26,856 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:26,957 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:26,957 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-22 18:28:26,958 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-22 18:28:26,958 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-22 18:28:26,958 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:27,059 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:27,059 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-22 18:28:27,061 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-22 18:28:27,061 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-22 18:28:27,061 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:27,161 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:27,162 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-22 18:28:27,162 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-22 18:28:27,163 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-22 18:28:27,163 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:27,263 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:27,264 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-22 18:28:27,264 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-22 18:28:27,264 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-22 18:28:27,265 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:27,365 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:27,366 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-22 18:28:27,366 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-22 18:28:27,366 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-22 18:28:27,366 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:27,467 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:27,468 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Connection complete.
2025-05-22 18:28:27,468 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: socket disconnected
2025-05-22 18:28:27,468 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connected> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: socket disconnected
2025-05-22 18:28:27,469 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:27,569 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:27,570 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Connect attempt returned error 111. Disconnecting.
2025-05-22 18:28:27,571 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-05-22 18:28:27,571 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:27,656 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:27,656 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Connect attempt returned error 111. Disconnecting.
2025-05-22 18:28:27,656 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-05-22 18:28:27,657 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:27,843 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:27,844 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Connect attempt returned error 111. Disconnecting.
2025-05-22 18:28:27,844 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-05-22 18:28:27,844 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:28,292 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:28,292 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Connect attempt returned error 111. Disconnecting.
2025-05-22 18:28:28,292 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-05-22 18:28:28,292 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:29,028 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:29,028 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Connect attempt returned error 111. Disconnecting.
2025-05-22 18:28:29,028 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-05-22 18:28:29,028 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:30,314 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:30,315 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Connect attempt returned error 111. Disconnecting.
2025-05-22 18:28:30,315 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-05-22 18:28:30,315 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:33,645 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: connecting to localhost:29092 [('127.0.0.1', 29092) IPv4]
2025-05-22 18:28:33,646 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Connect attempt returned error 111. Disconnecting.
2025-05-22 18:28:33,646 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:29092 <connecting> [IPv4 ('127.0.0.1', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
2025-05-22 18:28:33,646 - kafka.client - WARNING - Node 1 connection failed -- refreshing metadata
2025-05-22 18:28:38,047 - app.main - INFO - Civil Status Service shutting down...
2025-05-22 18:28:38,047 - app.services.reconciliation - INFO - Reconciliation service stopped
2025-05-22 18:28:38,047 - app.services.outbox_processor - INFO - Outbox processor stopped
2025-05-22 18:28:38,047 - app.services.event_retry_worker - INFO - Event retry worker stopped
2025-05-22 18:28:38,047 - kafka.producer.kafka - INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
2025-05-22 18:28:38,047 - app.services.kafka_producer - INFO - Kafka producer closed.
